#日志
logging:
  level:
    org:
      springframework:
        web: TRACE
        security:
          oauth2: TRACE
          oauth2.client: TRACE
          oauth2.core: TRACE
          oauth2.server: TRACE

server:
  port: 9000
spring:
  application:
    name: authorization-server
jwt:
  private:
    key: classpath:private.key
  public:
    key: classpath:public.key
